spring: 
    profiles: 
        active: 
            - dev
xuhao: 33
---
spring: 
    profiles: dev
    application: 
        name: configProvider-dev
---
spring: 
    profiles: test
    application: 
        name: configProvider-test
